version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - '27019:27017'
      
    restart: always

  server:
    image: 'faheemsiddiqi/cirspycrustco'
    ports:
      - "80:8080"
    restart: always
    depends_on:
      - mongodb

volumes:
  data:
  
